name: Build and Deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start Build Prompt
        run: echo Starting Build!
      - name: Build Using Npm
        run: |
          npm install
          npm run build
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v2.0.1
        with:
          token: ${{ github.token }}
          timeout: 600000
          error_count: 10
          reporting_interval: 5000
          artifact_name: github-pages
          preview: false

